---
server:
  port: 8001
spring:
  application:
    name: eureka-server
  profiles: reg1
eureka:
  instance:
    hostname: replica1
  client:
    serviceUrl:
      defaultZone: http://replica2:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
---
server:
  port: 8002
spring:
  application:
    name: eureka-server
  profiles: reg2
eureka:
  instance:
    hostname: replica2
  client:
    serviceUrl:
      defaultZone: http://replica1:8001/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true