eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
     defaultZone: http://replica1:8001/eureka/,http://replica2:8002/eureka/ #配置注册中心地址
spring:
  application:
    name: shop-gate-way
server:
  port: 9000
zuul:
  host: #(跟以上routes同等级)
   connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
   socket-timeout-millis: 60000   #socket超时
  #路由规则
  routes:
    shop-cate-api:
      path: /cate/**
    shop-goods-api:
      path: /goods/**
    shop-member-api:
      path: /member/**
fh:
  shop:
   checkUrls: /shop-member-api/api/member/findMember,/shop-member-api/api/member/logout,/shop-cart/api/cart/addCartItem,/shop-cart/api/cart/findCart,/shop-cart/api/cart/deleteCart,/shop-cart/api/cart/deleteBatch